import { Geist, Geist_Mono, Noto_Sans_Devanagari } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoDev = Noto_Sans_Devanagari({
  variable: "--font-noto-dev",
  subsets: ["devanagari"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoDev.variable} antialiased`}
        style={{ background: "var(--background)", color: "var(--foreground)" }}>
        {/* Skip to content for accessibility */}
        <a href="#content" className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 bg-surface border border-muted px-3 py-2 rounded">Skip to content</a>
        <header className="sticky top-0 z-20 border-b border-muted" style={{ background: "color-mix(in oklab, var(--background) 85%, transparent)" }}>
          <NavBar />
        </header>
        <main id="content" className="min-h-[calc(100vh-4rem)] container mx-auto px-4 py-4 animate-fade-in">
          {children}
        </main>
        <footer className="border-t border-muted text-xs text-gray-500 px-4 py-3">
          <div className="container mx-auto">
            <span>© {new Date().getFullYear()} सशस्त्र प्रहरी बल, नेपाल — ANPR & Smart Monitoring System</span>
            <span className="ml-2">Developed by BASAN-TA</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
