# Generated by Django 4.2.25 on 2025-11-01 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=32)),
                ('path', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('suspicious', 'Suspicious'), ('stolen', 'Stolen')], default='normal', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=128)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=64)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0)),
                ('heading_deg', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('suspicious', 'Suspicious'), ('stolen', 'Stolen')], max_length=16)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('predicted_latitude', models.FloatField(blank=True, null=True)),
                ('predicted_longitude', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('acknowledged', models.BooleanField(default=False)),
                ('dispatched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.vehicle')),
            ],
        ),
    ]
