# Generated by Django 4.2.25 on 2025-11-01 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=256)),
                ('flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceVehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=64, unique=True)),
                ('plate_number', models.CharField(max_length=32)),
                ('make', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('owner_name', models.CharField(blank=True, default='', max_length=128)),
                ('region_code', models.CharField(blank=True, default='', max_length=32)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StolenVehicleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=64, unique=True)),
                ('plate_number', models.CharField(max_length=32)),
                ('report_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('region_code', models.CharField(blank=True, default='', max_length=32)),
                ('details', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stolen_reports', to='core.policevehicleregistration')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_payload', models.JSONField(default=dict)),
                ('match_status', models.BooleanField(default=False)),
                ('flag_category', models.CharField(default='normal', max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('verification_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('reference_case_numbers', models.JSONField(default=list)),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_owner_watchlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='core.ownerwatchlist')),
                ('matched_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='core.policevehicleregistration')),
                ('matched_stolen_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='core.stolenvehiclereport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policevehicleregistration',
            index=models.Index(fields=['plate_number'], name='core_police_plate_n_18deeb_idx'),
        ),
        migrations.AddIndex(
            model_name='policevehicleregistration',
            index=models.Index(fields=['owner_name'], name='core_police_owner_n_e034e3_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerwatchlist',
            index=models.Index(fields=['owner_name'], name='core_ownerw_owner_n_d23281_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerwatchlist',
            index=models.Index(fields=['active'], name='core_ownerw_active_925dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='stolenvehiclereport',
            index=models.Index(fields=['plate_number'], name='core_stolen_plate_n_4a808c_idx'),
        ),
        migrations.AddIndex(
            model_name='stolenvehiclereport',
            index=models.Index(fields=['status'], name='core_stolen_status_58f995_idx'),
        ),
    ]
