# Generated by Django 4.2.25 on 2025-11-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ownerwatchlist_policevehicleregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=64, unique=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('records_vehicles', models.IntegerField(default=0)),
                ('records_sightings', models.IntegerField(default=0)),
                ('records_alerts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['version_label'], name='core_datase_version_0486a4_idx'), models.Index(fields=['applied_at'], name='core_datase_applied_502d0a_idx')],
            },
        ),
    ]
